import type { TraitConfig, ScoringAlgorithm, InputType, ScoringType } from '../schema';

export interface AssessmentSeedData {
  slug: string;
  category: string;
  name: string;
  popularEquivalent: string;
  scientificReference: string;
  description: string;
  questionCount: number;
  estimatedTime: string;
  scoringAlgorithm: ScoringAlgorithm;
  scoringType: ScoringType;
  inputType: InputType;
  traitConfig: TraitConfig;
  measurementClass: 'trait' | 'state';
  retestIntervalDays: number;
  oneTime?: boolean;
  questions: QuestionSeedData[];
}

export interface QuestionSeedData {
  questionNumber: number;
  text: string;
  traitKey: string;
  facetKey?: string;
  subCategory?: string;
  reverseCoded: boolean;
  correctOption?: string;
  options?: { value: string; label: string }[];
}

export const BIG_FIVE_TRAIT_CONFIG: TraitConfig = {
  traits: [
    { key: 'N', name: 'Neuroticism', description: 'Tendency to experience negative emotions', color: '#ef4444' },
    { key: 'E', name: 'Extraversion', description: 'Tendency to seek stimulation and enjoy company', color: '#f59e0b' },
    { key: 'O', name: 'Openness', description: 'Appreciation for art, emotion, and adventure', color: '#8b5cf6' },
    { key: 'A', name: 'Agreeableness', description: 'Tendency to be compassionate and cooperative', color: '#10b981' },
    { key: 'C', name: 'Conscientiousness', description: 'Tendency to be organized and dependable', color: '#3b82f6' },
  ],
  facets: [
    { key: 'N1', name: 'Anxiety', parentTrait: 'N' },
    { key: 'N2', name: 'Anger', parentTrait: 'N' },
    { key: 'N3', name: 'Depression', parentTrait: 'N' },
    { key: 'N4', name: 'Self-Consciousness', parentTrait: 'N' },
    { key: 'N5', name: 'Immoderation', parentTrait: 'N' },
    { key: 'N6', name: 'Vulnerability', parentTrait: 'N' },
    { key: 'E1', name: 'Friendliness', parentTrait: 'E' },
    { key: 'E2', name: 'Gregariousness', parentTrait: 'E' },
    { key: 'E3', name: 'Assertiveness', parentTrait: 'E' },
    { key: 'E4', name: 'Activity Level', parentTrait: 'E' },
    { key: 'E5', name: 'Excitement-Seeking', parentTrait: 'E' },
    { key: 'E6', name: 'Cheerfulness', parentTrait: 'E' },
    { key: 'O1', name: 'Imagination', parentTrait: 'O' },
    { key: 'O2', name: 'Artistic Interests', parentTrait: 'O' },
    { key: 'O3', name: 'Emotionality', parentTrait: 'O' },
    { key: 'O4', name: 'Adventurousness', parentTrait: 'O' },
    { key: 'O5', name: 'Intellect', parentTrait: 'O' },
    { key: 'O6', name: 'Liberalism', parentTrait: 'O' },
    { key: 'A1', name: 'Trust', parentTrait: 'A' },
    { key: 'A2', name: 'Morality', parentTrait: 'A' },
    { key: 'A3', name: 'Altruism', parentTrait: 'A' },
    { key: 'A4', name: 'Cooperation', parentTrait: 'A' },
    { key: 'A5', name: 'Modesty', parentTrait: 'A' },
    { key: 'A6', name: 'Sympathy', parentTrait: 'A' },
    { key: 'C1', name: 'Self-Efficacy', parentTrait: 'C' },
    { key: 'C2', name: 'Orderliness', parentTrait: 'C' },
    { key: 'C3', name: 'Dutifulness', parentTrait: 'C' },
    { key: 'C4', name: 'Achievement-Striving', parentTrait: 'C' },
    { key: 'C5', name: 'Self-Discipline', parentTrait: 'C' },
    { key: 'C6', name: 'Cautiousness', parentTrait: 'C' },
  ],
};

export const IPIP_NEO_120: AssessmentSeedData = {
  slug: 'ipip-neo-120',
  measurementClass: 'trait',
  retestIntervalDays: 365,
  category: 'Who Am I',
  name: 'IPIP-NEO-120',
  popularEquivalent: 'Similar to MBTI / 16 Personalities',
  scientificReference: 'Goldberg (1999)',
  description: 'The scientific gold standard for personality profiling. Measures the Big Five traits: Openness, Conscientiousness, Extraversion, Agreeableness, and Neuroticism.',
  questionCount: 120,
  estimatedTime: '15-20 mins',
  scoringAlgorithm: 'average',
  scoringType: 'likert_average',
  inputType: 'likert_5',
  traitConfig: BIG_FIVE_TRAIT_CONFIG,
  questions: [
    { questionNumber: 1, text: "Worry about things.", traitKey: 'N', facetKey: 'N1', reverseCoded: false },
    { questionNumber: 2, text: "Make friends easily.", traitKey: 'E', facetKey: 'E1', reverseCoded: false },
    { questionNumber: 3, text: "Have a vivid imagination.", traitKey: 'O', facetKey: 'O1', reverseCoded: false },
    { questionNumber: 4, text: "Trust others.", traitKey: 'A', facetKey: 'A1', reverseCoded: false },
    { questionNumber: 5, text: "Complete tasks successfully.", traitKey: 'C', facetKey: 'C1', reverseCoded: false },
    { questionNumber: 6, text: "Get angry easily.", traitKey: 'N', facetKey: 'N2', reverseCoded: false },
    { questionNumber: 7, text: "Love large parties.", traitKey: 'E', facetKey: 'E2', reverseCoded: false },
    { questionNumber: 8, text: "Believe in the importance of art.", traitKey: 'O', facetKey: 'O2', reverseCoded: false },
    { questionNumber: 9, text: "Use others for my own ends.", traitKey: 'A', facetKey: 'A2', reverseCoded: true },
    { questionNumber: 10, text: "Like to tidy up.", traitKey: 'C', facetKey: 'C2', reverseCoded: false },
    { questionNumber: 11, text: "Often feel blue.", traitKey: 'N', facetKey: 'N3', reverseCoded: false },
    { questionNumber: 12, text: "Take charge.", traitKey: 'E', facetKey: 'E3', reverseCoded: false },
    { questionNumber: 13, text: "Experience my emotions intensely.", traitKey: 'O', facetKey: 'O3', reverseCoded: false },
    { questionNumber: 14, text: "Love to help others.", traitKey: 'A', facetKey: 'A3', reverseCoded: false },
    { questionNumber: 15, text: "Keep my promises.", traitKey: 'C', facetKey: 'C3', reverseCoded: false },
    { questionNumber: 16, text: "Find it difficult to approach others.", traitKey: 'N', facetKey: 'N4', reverseCoded: false },
    { questionNumber: 17, text: "Am always busy.", traitKey: 'E', facetKey: 'E4', reverseCoded: false },
    { questionNumber: 18, text: "Prefer variety to routine.", traitKey: 'O', facetKey: 'O4', reverseCoded: false },
    { questionNumber: 19, text: "Love a good fight.", traitKey: 'A', facetKey: 'A4', reverseCoded: true },
    { questionNumber: 20, text: "Work hard.", traitKey: 'C', facetKey: 'C4', reverseCoded: false },
    { questionNumber: 21, text: "Go on binges.", traitKey: 'N', facetKey: 'N5', reverseCoded: false },
    { questionNumber: 22, text: "Love excitement.", traitKey: 'E', facetKey: 'E5', reverseCoded: false },
    { questionNumber: 23, text: "Love to read challenging material.", traitKey: 'O', facetKey: 'O5', reverseCoded: false },
    { questionNumber: 24, text: "Believe that I am better than others.", traitKey: 'A', facetKey: 'A5', reverseCoded: true },
    { questionNumber: 25, text: "Am always prepared.", traitKey: 'C', facetKey: 'C6', reverseCoded: false },
    { questionNumber: 26, text: "Panic easily.", traitKey: 'N', facetKey: 'N1', reverseCoded: false },
    { questionNumber: 27, text: "Radiate joy.", traitKey: 'E', facetKey: 'E6', reverseCoded: false },
    { questionNumber: 28, text: "Tend to vote for liberal political candidates.", traitKey: 'O', facetKey: 'O6', reverseCoded: false },
    { questionNumber: 29, text: "Sympathize with the homeless.", traitKey: 'A', facetKey: 'A6', reverseCoded: false },
    { questionNumber: 30, text: "Jump into things without thinking.", traitKey: 'C', facetKey: 'C6', reverseCoded: true },
    { questionNumber: 31, text: "Fear for the worst.", traitKey: 'N', facetKey: 'N1', reverseCoded: false },
    { questionNumber: 32, text: "Feel comfortable around people.", traitKey: 'E', facetKey: 'E1', reverseCoded: false },
    { questionNumber: 33, text: "Enjoy wild flights of fantasy.", traitKey: 'O', facetKey: 'O1', reverseCoded: false },
    { questionNumber: 34, text: "Believe that others have good intentions.", traitKey: 'A', facetKey: 'A1', reverseCoded: false },
    { questionNumber: 35, text: "Excel in what I do.", traitKey: 'C', facetKey: 'C1', reverseCoded: false },
    { questionNumber: 36, text: "Get irritated easily.", traitKey: 'N', facetKey: 'N2', reverseCoded: false },
    { questionNumber: 37, text: "Talk to a lot of different people at parties.", traitKey: 'E', facetKey: 'E2', reverseCoded: false },
    { questionNumber: 38, text: "See beauty in things that others might not notice.", traitKey: 'O', facetKey: 'O2', reverseCoded: false },
    { questionNumber: 39, text: "Cheat to get ahead.", traitKey: 'A', facetKey: 'A2', reverseCoded: true },
    { questionNumber: 40, text: "Often forget to put things back in their proper place.", traitKey: 'C', facetKey: 'C2', reverseCoded: true },
    { questionNumber: 41, text: "Dislike myself.", traitKey: 'N', facetKey: 'N3', reverseCoded: false },
    { questionNumber: 42, text: "Try to lead others.", traitKey: 'E', facetKey: 'E3', reverseCoded: false },
    { questionNumber: 43, text: "Feel others' emotions.", traitKey: 'O', facetKey: 'O3', reverseCoded: false },
    { questionNumber: 44, text: "Am concerned about others.", traitKey: 'A', facetKey: 'A3', reverseCoded: false },
    { questionNumber: 45, text: "Tell the truth.", traitKey: 'C', facetKey: 'C3', reverseCoded: false },
    { questionNumber: 46, text: "Am afraid to draw attention to myself.", traitKey: 'N', facetKey: 'N4', reverseCoded: false },
    { questionNumber: 47, text: "Am always on the go.", traitKey: 'E', facetKey: 'E4', reverseCoded: false },
    { questionNumber: 48, text: "Prefer to stick with things that I know.", traitKey: 'O', facetKey: 'O4', reverseCoded: true },
    { questionNumber: 49, text: "Yell at people.", traitKey: 'A', facetKey: 'A4', reverseCoded: true },
    { questionNumber: 50, text: "Do more than what's expected of me.", traitKey: 'C', facetKey: 'C4', reverseCoded: false },
    { questionNumber: 51, text: "Rarely overindulge.", traitKey: 'N', facetKey: 'N5', reverseCoded: true },
    { questionNumber: 52, text: "Seek adventure.", traitKey: 'E', facetKey: 'E5', reverseCoded: false },
    { questionNumber: 53, text: "Avoid philosophical discussions.", traitKey: 'O', facetKey: 'O5', reverseCoded: true },
    { questionNumber: 54, text: "Think highly of myself.", traitKey: 'A', facetKey: 'A5', reverseCoded: true },
    { questionNumber: 55, text: "Carry out my plans.", traitKey: 'C', facetKey: 'C5', reverseCoded: false },
    { questionNumber: 56, text: "Become overwhelmed by events.", traitKey: 'N', facetKey: 'N6', reverseCoded: false },
    { questionNumber: 57, text: "Have a lot of fun.", traitKey: 'E', facetKey: 'E6', reverseCoded: false },
    { questionNumber: 58, text: "Believe that there is no absolute right or wrong.", traitKey: 'O', facetKey: 'O6', reverseCoded: false },
    { questionNumber: 59, text: "Feel sympathy for those who are worse off than myself.", traitKey: 'A', facetKey: 'A6', reverseCoded: false },
    { questionNumber: 60, text: "Make rash decisions.", traitKey: 'C', facetKey: 'C6', reverseCoded: true },
    { questionNumber: 61, text: "Am afraid of many things.", traitKey: 'N', facetKey: 'N1', reverseCoded: false },
    { questionNumber: 62, text: "Avoid contacts with others.", traitKey: 'E', facetKey: 'E1', reverseCoded: true },
    { questionNumber: 63, text: "Love to daydream.", traitKey: 'O', facetKey: 'O1', reverseCoded: false },
    { questionNumber: 64, text: "Trust what people say.", traitKey: 'A', facetKey: 'A1', reverseCoded: false },
    { questionNumber: 65, text: "Handle tasks smoothly.", traitKey: 'C', facetKey: 'C1', reverseCoded: false },
    { questionNumber: 66, text: "Lose my temper.", traitKey: 'N', facetKey: 'N2', reverseCoded: false },
    { questionNumber: 67, text: "Prefer to be alone.", traitKey: 'E', facetKey: 'E2', reverseCoded: true },
    { questionNumber: 68, text: "Do not like poetry.", traitKey: 'O', facetKey: 'O2', reverseCoded: true },
    { questionNumber: 69, text: "Take advantage of others.", traitKey: 'A', facetKey: 'A2', reverseCoded: true },
    { questionNumber: 70, text: "Leave a mess in my room.", traitKey: 'C', facetKey: 'C2', reverseCoded: true },
    { questionNumber: 71, text: "Am often down in the dumps.", traitKey: 'N', facetKey: 'N3', reverseCoded: false },
    { questionNumber: 72, text: "Take control of things.", traitKey: 'E', facetKey: 'E3', reverseCoded: false },
    { questionNumber: 73, text: "Rarely notice my emotional reactions.", traitKey: 'O', facetKey: 'O3', reverseCoded: true },
    { questionNumber: 74, text: "Am indifferent to the feelings of others.", traitKey: 'A', facetKey: 'A3', reverseCoded: true },
    { questionNumber: 75, text: "Break rules.", traitKey: 'C', facetKey: 'C3', reverseCoded: true },
    { questionNumber: 76, text: "Only feel comfortable with friends.", traitKey: 'N', facetKey: 'N4', reverseCoded: false },
    { questionNumber: 77, text: "Do a lot in my spare time.", traitKey: 'E', facetKey: 'E4', reverseCoded: false },
    { questionNumber: 78, text: "Dislike changes.", traitKey: 'O', facetKey: 'O4', reverseCoded: true },
    { questionNumber: 79, text: "Insult people.", traitKey: 'A', facetKey: 'A4', reverseCoded: true },
    { questionNumber: 80, text: "Do just enough work to get by.", traitKey: 'C', facetKey: 'C4', reverseCoded: true },
    { questionNumber: 81, text: "Easily resist temptations.", traitKey: 'N', facetKey: 'N5', reverseCoded: true },
    { questionNumber: 82, text: "Enjoy being reckless.", traitKey: 'E', facetKey: 'E5', reverseCoded: false },
    { questionNumber: 83, text: "Have difficulty understanding abstract ideas.", traitKey: 'O', facetKey: 'O5', reverseCoded: true },
    { questionNumber: 84, text: "Have a high opinion of myself.", traitKey: 'A', facetKey: 'A5', reverseCoded: true },
    { questionNumber: 85, text: "Waste my time.", traitKey: 'C', facetKey: 'C5', reverseCoded: true },
    { questionNumber: 86, text: "Feel that I'm unable to deal with things.", traitKey: 'N', facetKey: 'N6', reverseCoded: false },
    { questionNumber: 87, text: "Love life.", traitKey: 'E', facetKey: 'E6', reverseCoded: false },
    { questionNumber: 88, text: "Tend to vote for conservative political candidates.", traitKey: 'O', facetKey: 'O6', reverseCoded: true },
    { questionNumber: 89, text: "Am not interested in other people's problems.", traitKey: 'A', facetKey: 'A6', reverseCoded: true },
    { questionNumber: 90, text: "Rush into things.", traitKey: 'C', facetKey: 'C6', reverseCoded: true },
    { questionNumber: 91, text: "Get stressed out easily.", traitKey: 'N', facetKey: 'N1', reverseCoded: false },
    { questionNumber: 92, text: "Keep in the background.", traitKey: 'E', facetKey: 'E3', reverseCoded: true },
    { questionNumber: 93, text: "Get carried away by my fantasies.", traitKey: 'O', facetKey: 'O1', reverseCoded: false },
    { questionNumber: 94, text: "Suspect hidden motives in others.", traitKey: 'A', facetKey: 'A1', reverseCoded: true },
    { questionNumber: 95, text: "Know how to get things done.", traitKey: 'C', facetKey: 'C1', reverseCoded: false },
    { questionNumber: 96, text: "Am not easily annoyed.", traitKey: 'N', facetKey: 'N2', reverseCoded: true },
    { questionNumber: 97, text: "Avoid crowds.", traitKey: 'E', facetKey: 'E2', reverseCoded: true },
    { questionNumber: 98, text: "Do not enjoy going to art museums.", traitKey: 'O', facetKey: 'O2', reverseCoded: true },
    { questionNumber: 99, text: "Obstruct others' plans.", traitKey: 'A', facetKey: 'A4', reverseCoded: true },
    { questionNumber: 100, text: "Leave my belongings around.", traitKey: 'C', facetKey: 'C2', reverseCoded: true },
    { questionNumber: 101, text: "Feel comfortable with myself.", traitKey: 'N', facetKey: 'N3', reverseCoded: true },
    { questionNumber: 102, text: "Wait for others to lead the way.", traitKey: 'E', facetKey: 'E3', reverseCoded: true },
    { questionNumber: 103, text: "Don't understand people who get emotional.", traitKey: 'O', facetKey: 'O3', reverseCoded: true },
    { questionNumber: 104, text: "Take no time for others.", traitKey: 'A', facetKey: 'A3', reverseCoded: true },
    { questionNumber: 105, text: "Break my promises.", traitKey: 'C', facetKey: 'C3', reverseCoded: true },
    { questionNumber: 106, text: "Am not bothered by difficult social situations.", traitKey: 'N', facetKey: 'N4', reverseCoded: true },
    { questionNumber: 107, text: "Like to take it easy.", traitKey: 'E', facetKey: 'E4', reverseCoded: true },
    { questionNumber: 108, text: "Am attached to conventional ways.", traitKey: 'O', facetKey: 'O4', reverseCoded: true },
    { questionNumber: 109, text: "Get back at others.", traitKey: 'A', facetKey: 'A4', reverseCoded: true },
    { questionNumber: 110, text: "Put little time and effort into my work.", traitKey: 'C', facetKey: 'C4', reverseCoded: true },
    { questionNumber: 111, text: "Am able to control my cravings.", traitKey: 'N', facetKey: 'N5', reverseCoded: true },
    { questionNumber: 112, text: "Act wild and crazy.", traitKey: 'E', facetKey: 'E5', reverseCoded: false },
    { questionNumber: 113, text: "Am not interested in theoretical discussions.", traitKey: 'O', facetKey: 'O5', reverseCoded: true },
    { questionNumber: 114, text: "Boast about my virtues.", traitKey: 'A', facetKey: 'A5', reverseCoded: true },
    { questionNumber: 115, text: "Have difficulty starting tasks.", traitKey: 'C', facetKey: 'C5', reverseCoded: true },
    { questionNumber: 116, text: "Remain calm under pressure.", traitKey: 'N', facetKey: 'N6', reverseCoded: true },
    { questionNumber: 117, text: "Look at the bright side of life.", traitKey: 'E', facetKey: 'E6', reverseCoded: false },
    { questionNumber: 118, text: "Believe that we should be tough on crime.", traitKey: 'O', facetKey: 'O6', reverseCoded: true },
    { questionNumber: 119, text: "Try not to think about the needy.", traitKey: 'A', facetKey: 'A6', reverseCoded: true },
    { questionNumber: 120, text: "Act without thinking.", traitKey: 'C', facetKey: 'C6', reverseCoded: true },
  ],
};

export const PVQ_VALUES_TRAIT_CONFIG: TraitConfig = {
  traits: [
    { key: 'PO', name: 'Power', description: 'Social status, control over resources and people', color: '#7c3aed' },
    { key: 'AC', name: 'Achievement', description: 'Personal success through demonstrating competence', color: '#f59e0b' },
    { key: 'HE', name: 'Hedonism', description: 'Pleasure and sensuous gratification', color: '#ec4899' },
    { key: 'ST', name: 'Stimulation', description: 'Excitement, novelty, and challenge in life', color: '#ef4444' },
    { key: 'SD', name: 'Self-Direction', description: 'Independent thought and action', color: '#3b82f6' },
    { key: 'UN', name: 'Universalism', description: 'Understanding, tolerance, and protection for all', color: '#10b981' },
    { key: 'BE', name: 'Benevolence', description: 'Preserving and enhancing welfare of close others', color: '#06b6d4' },
    { key: 'TR', name: 'Tradition', description: 'Respect and commitment to cultural customs', color: '#78716c' },
    { key: 'CO', name: 'Conformity', description: 'Restraint of actions likely to harm others', color: '#64748b' },
    { key: 'SE', name: 'Security', description: 'Safety, harmony, and stability', color: '#22c55e' },
  ],
};

export const SCHWARTZ_PVQ_21: AssessmentSeedData = {
  slug: 'schwartz-pvq-21',
  measurementClass: 'trait',
  retestIntervalDays: 365,
  category: 'Who Am I',
  name: 'Schwartz Portrait Values (PVQ)',
  popularEquivalent: 'Similar to Enneagram',
  scientificReference: 'Schwartz (1992)',
  description: 'Identifies your core drivers and motivations (e.g., Tradition, Power, Benevolence) rather than just behavior.',
  questionCount: 21,
  estimatedTime: '5-7 mins',
  scoringAlgorithm: 'complex_centering',
  scoringType: 'likert_average',
  inputType: 'likert_6',
  traitConfig: PVQ_VALUES_TRAIT_CONFIG,
  questions: [
    { questionNumber: 1, text: "Thinking up new ideas and being creative is important to this person. This person likes to do things in their own original way.", traitKey: 'SD', reverseCoded: false },
    { questionNumber: 2, text: "It is important to this person to be rich. This person wants to have a lot of money and expensive things.", traitKey: 'PO', reverseCoded: false },
    { questionNumber: 3, text: "This person thinks it is important that every person in the world should be treated equally. This person believes everyone should have equal opportunities in life.", traitKey: 'UN', reverseCoded: false },
    { questionNumber: 4, text: "It is important to this person to show their abilities. This person wants people to admire what they do.", traitKey: 'AC', reverseCoded: false },
    { questionNumber: 5, text: "It is important to this person to live in secure surroundings. This person avoids anything that might endanger their safety.", traitKey: 'SE', reverseCoded: false },
    { questionNumber: 6, text: "This person thinks it is important to do lots of different things in life. This person always looks for new things to try.", traitKey: 'ST', reverseCoded: false },
    { questionNumber: 7, text: "This person believes that people should do what they're told. This person thinks people should follow rules at all times, even when no one is watching.", traitKey: 'CO', reverseCoded: false },
    { questionNumber: 8, text: "It is important to this person to listen to people who are different from them. Even when this person disagrees with them, they still want to understand them.", traitKey: 'UN', reverseCoded: false },
    { questionNumber: 9, text: "This person thinks it is important not to ask for more than what you have. This person believes that people should be satisfied with what they have.", traitKey: 'TR', reverseCoded: false },
    { questionNumber: 10, text: "This person seeks every chance they can to have fun. It is important to this person to do things that give them pleasure.", traitKey: 'HE', reverseCoded: false },
    { questionNumber: 11, text: "It is important to this person to make their own decisions about what they do. This person likes to be free and not depend on others.", traitKey: 'SD', reverseCoded: false },
    { questionNumber: 12, text: "It is very important to this person to help the people around them. This person wants to care for their well-being.", traitKey: 'BE', reverseCoded: false },
    { questionNumber: 13, text: "Being very successful is important to this person. This person hopes people will recognize their achievements.", traitKey: 'AC', reverseCoded: false },
    { questionNumber: 14, text: "It is important to this person that the government ensures their safety against all threats. This person wants the state to be strong so it can defend its citizens.", traitKey: 'SE', reverseCoded: false },
    { questionNumber: 15, text: "This person looks for adventures and likes to take risks. This person wants to have an exciting life.", traitKey: 'ST', reverseCoded: false },
    { questionNumber: 16, text: "It is important to this person always to behave properly. This person wants to avoid doing anything people would say is wrong.", traitKey: 'CO', reverseCoded: false },
    { questionNumber: 17, text: "It is important to this person to get respect from others. This person wants people to do what they say.", traitKey: 'PO', reverseCoded: false },
    { questionNumber: 18, text: "It is important to this person to be loyal to their friends. This person wants to devote themselves to people close to them.", traitKey: 'BE', reverseCoded: false },
    { questionNumber: 19, text: "This person strongly believes that people should care for nature. Looking after the environment is important to this person.", traitKey: 'UN', reverseCoded: false },
    { questionNumber: 20, text: "Tradition is important to this person. This person tries to follow the customs handed down by their religion or their family.", traitKey: 'TR', reverseCoded: false },
    { questionNumber: 21, text: "This person seeks every opportunity to have a good time. It is important to them to enjoy life's pleasures.", traitKey: 'HE', reverseCoded: false },
  ],
};

export const DARK_TRIAD_TRAIT_CONFIG: TraitConfig = {
  traits: [
    { key: 'MACH', name: 'Machiavellianism', description: 'Manipulation and exploitation of others, cynical disregard for morality', color: '#1e293b' },
    { key: 'NARC', name: 'Narcissism', description: 'Grandiosity, pride, egotism, and lack of empathy', color: '#7c3aed' },
    { key: 'PSYC', name: 'Psychopathy', description: 'Antisocial behavior, impulsivity, selfishness, callousness', color: '#dc2626' },
  ],
  populationAverages: {
    MACH: 3.1,
    NARC: 2.8,
    PSYC: 2.1,
  },
};

export const SHORT_DARK_TRIAD_SD3: AssessmentSeedData = {
  slug: 'short-dark-triad-sd3',
  measurementClass: 'trait',
  retestIntervalDays: 365,
  category: 'Who Am I',
  name: 'Short Dark Triad (SD3)',
  popularEquivalent: 'Dark Personality Assessment',
  scientificReference: 'Jones & Paulhus (2014)',
  description: 'Measures the three socially aversive traits: Machiavellianism, Narcissism, and Psychopathy. Used in organizational and clinical psychology.',
  questionCount: 27,
  estimatedTime: '5-7 mins',
  scoringAlgorithm: 'summation',
  scoringType: 'likert_sum',
  inputType: 'likert_5',
  traitConfig: DARK_TRIAD_TRAIT_CONFIG,
  questions: [
    { questionNumber: 1, text: "It's not wise to tell your secrets.", traitKey: 'MACH', reverseCoded: false },
    { questionNumber: 2, text: "I like to use clever manipulation to get my way.", traitKey: 'MACH', reverseCoded: false },
    { questionNumber: 3, text: "Whatever it takes, you must get the important people on your side.", traitKey: 'MACH', reverseCoded: false },
    { questionNumber: 4, text: "Avoid direct conflict with others because they may be useful in the future.", traitKey: 'MACH', reverseCoded: false },
    { questionNumber: 5, text: "It's wise to keep track of information that you can use against people later.", traitKey: 'MACH', reverseCoded: false },
    { questionNumber: 6, text: "You should wait for the right time to get back at people.", traitKey: 'MACH', reverseCoded: false },
    { questionNumber: 7, text: "There are things you should hide from other people to preserve your reputation.", traitKey: 'MACH', reverseCoded: false },
    { questionNumber: 8, text: "Make sure your plans benefit yourself, not others.", traitKey: 'MACH', reverseCoded: false },
    { questionNumber: 9, text: "Most people can be manipulated.", traitKey: 'MACH', reverseCoded: false },
    { questionNumber: 10, text: "People see me as a natural leader.", traitKey: 'NARC', reverseCoded: false },
    { questionNumber: 11, text: "I hate being the center of attention.", traitKey: 'NARC', reverseCoded: true },
    { questionNumber: 12, text: "Many group activities tend to be dull without me.", traitKey: 'NARC', reverseCoded: false },
    { questionNumber: 13, text: "I know that I am special because everyone keeps telling me so.", traitKey: 'NARC', reverseCoded: false },
    { questionNumber: 14, text: "I like to get acquainted with important people.", traitKey: 'NARC', reverseCoded: false },
    { questionNumber: 15, text: "I feel embarrassed if someone compliments me.", traitKey: 'NARC', reverseCoded: true },
    { questionNumber: 16, text: "I have been compared to famous people.", traitKey: 'NARC', reverseCoded: false },
    { questionNumber: 17, text: "I am an average person.", traitKey: 'NARC', reverseCoded: true },
    { questionNumber: 18, text: "I insist on getting the respect I deserve.", traitKey: 'NARC', reverseCoded: false },
    { questionNumber: 19, text: "I like to get revenge on authorities.", traitKey: 'PSYC', reverseCoded: false },
    { questionNumber: 20, text: "I avoid dangerous situations.", traitKey: 'PSYC', reverseCoded: true },
    { questionNumber: 21, text: "Payback needs to be quick and nasty.", traitKey: 'PSYC', reverseCoded: false },
    { questionNumber: 22, text: "People often say I'm out of control.", traitKey: 'PSYC', reverseCoded: false },
    { questionNumber: 23, text: "It's true that I can be mean to others.", traitKey: 'PSYC', reverseCoded: false },
    { questionNumber: 24, text: "People who mess with me always regret it.", traitKey: 'PSYC', reverseCoded: false },
    { questionNumber: 25, text: "I have never gotten into trouble with the law.", traitKey: 'PSYC', reverseCoded: true },
    { questionNumber: 26, text: "I enjoy having sex with people I hardly know.", traitKey: 'PSYC', reverseCoded: false },
    { questionNumber: 27, text: "I'll say anything to get what I want.", traitKey: 'PSYC', reverseCoded: false },
  ],
};

export const CATEGORY_ONE_ASSESSMENTS: AssessmentSeedData[] = [
  IPIP_NEO_120,
  SCHWARTZ_PVQ_21,
  SHORT_DARK_TRIAD_SD3,
];

export const LIKERT_SCALES = {
  likert_5: [
    { value: 1, label: 'Very Inaccurate' },
    { value: 2, label: 'Moderately Inaccurate' },
    { value: 3, label: 'Neither Accurate Nor Inaccurate' },
    { value: 4, label: 'Moderately Accurate' },
    { value: 5, label: 'Very Accurate' },
  ],
  likert_6: [
    { value: 6, label: 'Very much like me' },
    { value: 5, label: 'Like me' },
    { value: 4, label: 'Somewhat like me' },
    { value: 3, label: 'A little like me' },
    { value: 2, label: 'Not like me' },
    { value: 1, label: 'Not like me at all' },
  ],
  likert_7: [
    { value: 1, label: 'Strongly Disagree' },
    { value: 2, label: 'Disagree' },
    { value: 3, label: 'Somewhat Disagree' },
    { value: 4, label: 'Neutral' },
    { value: 5, label: 'Somewhat Agree' },
    { value: 6, label: 'Agree' },
    { value: 7, label: 'Strongly Agree' },
  ],
};
