export type TraitKey = 'N' | 'E' | 'O' | 'A' | 'C';

export interface Question {
  id: number;
  text: string;
  trait: TraitKey;
  keyed: '+' | '-';
}

export const traitNames: Record<TraitKey, string> = {
  N: 'Neuroticism',
  E: 'Extraversion',
  O: 'Openness',
  A: 'Agreeableness',
  C: 'Conscientiousness',
};

export const traitDescriptions: Record<TraitKey, string> = {
  N: 'Tendency to experience negative emotions like anxiety, anger, or depression',
  E: 'Tendency to seek stimulation and enjoy the company of others',
  O: 'Appreciation for art, emotion, adventure, and unusual ideas',
  A: 'Tendency to be compassionate and cooperative toward others',
  C: 'Tendency to be organized, dependable, and self-disciplined',
};

export const questions: Question[] = [
  { id: 1, text: "Worry about things.", trait: 'N', keyed: '+' },
  { id: 2, text: "Make friends easily.", trait: 'E', keyed: '+' },
  { id: 3, text: "Have a vivid imagination.", trait: 'O', keyed: '+' },
  { id: 4, text: "Trust others.", trait: 'A', keyed: '+' },
  { id: 5, text: "Complete tasks successfully.", trait: 'C', keyed: '+' },
  { id: 6, text: "Get angry easily.", trait: 'N', keyed: '+' },
  { id: 7, text: "Love large parties.", trait: 'E', keyed: '+' },
  { id: 8, text: "Believe in the importance of art.", trait: 'O', keyed: '+' },
  { id: 9, text: "Use others for my own ends.", trait: 'A', keyed: '-' },
  { id: 10, text: "Like to tidy up.", trait: 'C', keyed: '+' },
  { id: 11, text: "Often feel blue.", trait: 'N', keyed: '+' },
  { id: 12, text: "Take charge.", trait: 'E', keyed: '+' },
  { id: 13, text: "Experience my emotions intensely.", trait: 'O', keyed: '+' },
  { id: 14, text: "Love to help others.", trait: 'A', keyed: '+' },
  { id: 15, text: "Keep my promises.", trait: 'C', keyed: '+' },
  { id: 16, text: "Find it difficult to approach others.", trait: 'N', keyed: '+' },
  { id: 17, text: "Am always busy.", trait: 'E', keyed: '+' },
  { id: 18, text: "Prefer variety to routine.", trait: 'O', keyed: '+' },
  { id: 19, text: "Love a good fight.", trait: 'A', keyed: '-' },
  { id: 20, text: "Work hard.", trait: 'C', keyed: '+' },
  { id: 21, text: "Go on binges.", trait: 'N', keyed: '+' },
  { id: 22, text: "Love excitement.", trait: 'E', keyed: '+' },
  { id: 23, text: "Love to read challenging material.", trait: 'O', keyed: '+' },
  { id: 24, text: "Believe that I am better than others.", trait: 'A', keyed: '-' },
  { id: 25, text: "Am always prepared.", trait: 'C', keyed: '+' },
  { id: 26, text: "Panic easily.", trait: 'N', keyed: '+' },
  { id: 27, text: "Radiate joy.", trait: 'E', keyed: '+' },
  { id: 28, text: "Tend to vote for liberal political candidates.", trait: 'O', keyed: '+' },
  { id: 29, text: "Sympathize with the homeless.", trait: 'A', keyed: '+' },
  { id: 30, text: "Jump into things without thinking.", trait: 'C', keyed: '-' },
  { id: 31, text: "Fear for the worst.", trait: 'N', keyed: '+' },
  { id: 32, text: "Feel comfortable around people.", trait: 'E', keyed: '+' },
  { id: 33, text: "Enjoy wild flights of fantasy.", trait: 'O', keyed: '+' },
  { id: 34, text: "Believe that others have good intentions.", trait: 'A', keyed: '+' },
  { id: 35, text: "Excel in what I do.", trait: 'C', keyed: '+' },
  { id: 36, text: "Get irritated easily.", trait: 'N', keyed: '+' },
  { id: 37, text: "Talk to a lot of different people at parties.", trait: 'E', keyed: '+' },
  { id: 38, text: "See beauty in things that others might not notice.", trait: 'O', keyed: '+' },
  { id: 39, text: "Cheat to get ahead.", trait: 'A', keyed: '-' },
  { id: 40, text: "Often forget to put things back in their proper place.", trait: 'C', keyed: '-' },
  { id: 41, text: "Dislike myself.", trait: 'N', keyed: '+' },
  { id: 42, text: "Try to lead others.", trait: 'E', keyed: '+' },
  { id: 43, text: "Feel others' emotions.", trait: 'O', keyed: '+' },
  { id: 44, text: "Am concerned about others.", trait: 'A', keyed: '+' },
  { id: 45, text: "Tell the truth.", trait: 'C', keyed: '+' },
  { id: 46, text: "Am afraid to draw attention to myself.", trait: 'N', keyed: '+' },
  { id: 47, text: "Am always on the go.", trait: 'E', keyed: '+' },
  { id: 48, text: "Prefer to stick with things that I know.", trait: 'O', keyed: '-' },
  { id: 49, text: "Yell at people.", trait: 'A', keyed: '-' },
  { id: 50, text: "Do more than what's expected of me.", trait: 'C', keyed: '+' },
  { id: 51, text: "Rarely overindulge.", trait: 'N', keyed: '-' },
  { id: 52, text: "Seek adventure.", trait: 'E', keyed: '+' },
  { id: 53, text: "Avoid philosophical discussions.", trait: 'O', keyed: '-' },
  { id: 54, text: "Think highly of myself.", trait: 'A', keyed: '-' },
  { id: 55, text: "Carry out my plans.", trait: 'C', keyed: '+' },
  { id: 56, text: "Become overwhelmed by events.", trait: 'N', keyed: '+' },
  { id: 57, text: "Have a lot of fun.", trait: 'E', keyed: '+' },
  { id: 58, text: "Believe that there is no absolute right or wrong.", trait: 'O', keyed: '+' },
  { id: 59, text: "Feel sympathy for those who are worse off than myself.", trait: 'A', keyed: '+' },
  { id: 60, text: "Make rash decisions.", trait: 'C', keyed: '-' },
  { id: 61, text: "Am afraid of many things.", trait: 'N', keyed: '+' },
  { id: 62, text: "Avoid contacts with others.", trait: 'E', keyed: '-' },
  { id: 63, text: "Love to daydream.", trait: 'O', keyed: '+' },
  { id: 64, text: "Trust what people say.", trait: 'A', keyed: '+' },
  { id: 65, text: "Handle tasks smoothly.", trait: 'C', keyed: '+' },
  { id: 66, text: "Lose my temper.", trait: 'N', keyed: '+' },
  { id: 67, text: "Prefer to be alone.", trait: 'E', keyed: '-' },
  { id: 68, text: "Do not like poetry.", trait: 'O', keyed: '-' },
  { id: 69, text: "Take advantage of others.", trait: 'A', keyed: '-' },
  { id: 70, text: "Leave a mess in my room.", trait: 'C', keyed: '-' },
  { id: 71, text: "Am often down in the dumps.", trait: 'N', keyed: '+' },
  { id: 72, text: "Take control of things.", trait: 'E', keyed: '+' },
  { id: 73, text: "Rarely notice my emotional reactions.", trait: 'O', keyed: '-' },
  { id: 74, text: "Am indifferent to the feelings of others.", trait: 'A', keyed: '-' },
  { id: 75, text: "Break rules.", trait: 'C', keyed: '-' },
  { id: 76, text: "Only feel comfortable with friends.", trait: 'N', keyed: '+' },
  { id: 77, text: "Do a lot in my spare time.", trait: 'E', keyed: '+' },
  { id: 78, text: "Dislike changes.", trait: 'O', keyed: '-' },
  { id: 79, text: "Insult people.", trait: 'A', keyed: '-' },
  { id: 80, text: "Do just enough work to get by.", trait: 'C', keyed: '-' },
  { id: 81, text: "Easily resist temptations.", trait: 'N', keyed: '-' },
  { id: 82, text: "Enjoy being reckless.", trait: 'E', keyed: '+' },
  { id: 83, text: "Have difficulty understanding abstract ideas.", trait: 'O', keyed: '-' },
  { id: 84, text: "Have a high opinion of myself.", trait: 'A', keyed: '-' },
  { id: 85, text: "Waste my time.", trait: 'C', keyed: '-' },
  { id: 86, text: "Feel that I'm unable to deal with things.", trait: 'N', keyed: '+' },
  { id: 87, text: "Love life.", trait: 'E', keyed: '+' },
  { id: 88, text: "Tend to vote for conservative political candidates.", trait: 'O', keyed: '-' },
  { id: 89, text: "Am not interested in other people's problems.", trait: 'A', keyed: '-' },
  { id: 90, text: "Rush into things.", trait: 'C', keyed: '-' },
  { id: 91, text: "Get stressed out easily.", trait: 'N', keyed: '+' },
  { id: 92, text: "Keep in the background.", trait: 'E', keyed: '-' },
  { id: 93, text: "Get carried away by my fantasies.", trait: 'O', keyed: '+' },
  { id: 94, text: "Suspect hidden motives in others.", trait: 'A', keyed: '-' },
  { id: 95, text: "Know how to get things done.", trait: 'C', keyed: '+' },
  { id: 96, text: "Am not easily annoyed.", trait: 'N', keyed: '-' },
  { id: 97, text: "Avoid crowds.", trait: 'E', keyed: '-' },
  { id: 98, text: "Do not enjoy going to art museums.", trait: 'O', keyed: '-' },
  { id: 99, text: "Obstruct others' plans.", trait: 'A', keyed: '-' },
  { id: 100, text: "Leave my belongings around.", trait: 'C', keyed: '-' },
  { id: 101, text: "Feel comfortable with myself.", trait: 'N', keyed: '-' },
  { id: 102, text: "Wait for others to lead the way.", trait: 'E', keyed: '-' },
  { id: 103, text: "Don't understand people who get emotional.", trait: 'O', keyed: '-' },
  { id: 104, text: "Take no time for others.", trait: 'A', keyed: '-' },
  { id: 105, text: "Break my promises.", trait: 'C', keyed: '-' },
  { id: 106, text: "Am not bothered by difficult social situations.", trait: 'N', keyed: '-' },
  { id: 107, text: "Like to take it easy.", trait: 'E', keyed: '-' },
  { id: 108, text: "Am attached to conventional ways.", trait: 'O', keyed: '-' },
  { id: 109, text: "Get back at others.", trait: 'A', keyed: '-' },
  { id: 110, text: "Put little time and effort into my work.", trait: 'C', keyed: '-' },
  { id: 111, text: "Am able to control my cravings.", trait: 'N', keyed: '-' },
  { id: 112, text: "Act wild and crazy.", trait: 'E', keyed: '+' },
  { id: 113, text: "Am not interested in theoretical discussions.", trait: 'O', keyed: '-' },
  { id: 114, text: "Boast about my virtues.", trait: 'A', keyed: '-' },
  { id: 115, text: "Have difficulty starting tasks.", trait: 'C', keyed: '-' },
  { id: 116, text: "Remain calm under pressure.", trait: 'N', keyed: '-' },
  { id: 117, text: "Look at the bright side of life.", trait: 'E', keyed: '+' },
  { id: 118, text: "Believe that we should be tough on crime.", trait: 'O', keyed: '-' },
  { id: 119, text: "Try not to think about the needy.", trait: 'A', keyed: '-' },
  { id: 120, text: "Act without thinking.", trait: 'C', keyed: '-' },
];

export const traitQuestions: Record<TraitKey, number[]> = {
  N: [1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96, 101, 106, 111, 116],
  E: [2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92, 97, 102, 107, 112, 117],
  O: [3, 8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88, 93, 98, 103, 108, 113, 118],
  A: [4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99, 104, 109, 114, 119],
  C: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120],
};

export const likertScale = [
  { value: 1, label: 'Very Inaccurate' },
  { value: 2, label: 'Moderately Inaccurate' },
  { value: 3, label: 'Neither Accurate Nor Inaccurate' },
  { value: 4, label: 'Moderately Accurate' },
  { value: 5, label: 'Very Accurate' },
];
